//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diepmoctra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Image { get; set; }
        public string ImageSmall { get; set; }
        public Nullable<short> Width { get; set; }
        public Nullable<short> Height { get; set; }
        public string Link { get; set; }
        public string Target { get; set; }
        public string ContentDetail { get; set; }
        public Nullable<short> Position { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> Click { get; set; }
        public Nullable<short> Ord { get; set; }
        public Nullable<byte> Active { get; set; }
        public string Lang { get; set; }
    }
}
