//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diepmoctra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Summary { get; set; }
        public string ImageSmall { get; set; }
        public string Image { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<int> Ord { get; set; }
        public string Lang { get; set; }
    }
}
